<?php
/**
 * Created by PhpStorm.
 * User: kolya
 * Date: 29.06.2019
 * Time: 22:33
 */

namespace app\widgets;


use yii\base\Widget;

class SideBar extends  Widget
{
    public $popular;
    public $categories;
    public $resent;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('SideBarViews',[
            'popular'=>$this->popular,
            'categories'=>$this->categories,
            'resent'=>$this->resent
        ]);
    }


}